---
title: "Predict ratings for #TidyTuesday board games"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler", fig.width = 8, fig.height = 5)
library(reticulate)
library(tidyverse, quietly = TRUE)
theme_set(theme_minimal())
update_geom_defaults("rect", list(fill = "midnightblue", alpha = 0.8))
```

Original notebook: https://juliasilge.com/blog/board-games/

# Explore data

### Distribution average ratings

```{r}
ratings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/ratings.csv", col_types = cols())
details <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/details.csv", col_types = cols())

ratings_joined <-
  ratings %>%
  left_join(details, by = "id")

ggplot(ratings_joined, aes(average)) +
  geom_histogram(alpha = 0.8)
```

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ratings = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/ratings.csv")
details = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/details.csv")

ratings_joined = (
  ratings
  .join(details, on="id", how="left", lsuffix='.x', rsuffix='.y')
  .copy()
  )

plt.cla()
sns.histplot(data=ratings_joined, x="average", alpha=.8)
plt.show()
```

### Distribution minimum age

```{r}
ratings_joined %>%
  filter(!is.na(minage)) %>%
  mutate(minage = cut_number(minage, 4)) %>%
  ggplot(aes(minage, average, fill = minage)) +
  geom_boxplot(alpha = 0.2, show.legend = FALSE)
```


```{python}
p_df = (
ratings_joined
  [ratings_joined["minage"].notnull()]
  .assign(minage = lambda x: pd.cut(x["minage"], bins=4))
)

plt.cla()
ng = sns.boxplot(data=p_df, x="minage", y="average", hue="minage")
plt.legend([], [], frameon=False)
plt.show()
```


# Tune and xgboost model

### Train and test split

```{r}
library(tidymodels)

test <- 
ratings_joined %>%
  select(name, average, boardgamecategory, matches("min|max")) %>%
  na.omit() 
set.seed(123)
game_split <-
  ratings_joined %>%
  select(name, average, matches("min|max"), boardgamecategory) %>%
  na.omit() %>%
  initial_split(strata = average)
game_train <- training(game_split)
game_test <- testing(game_split)

set.seed(234)
game_folds <- vfold_cv(game_train, strata = average)
game_folds
```


```{python}
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split

np.random.seed(123)
df1 = (
ratings_joined
  .filter(["name","average", "boardgamecategory"])
)
df2 = (
ratings_joined
  .filter(regex=("min|max"))
)
game_split = pd.concat([df1, df2], axis=1)#.dropna()
```



